name: sp
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - numpy
  - scipy
  - pandas
  - xarray
  - netcdf4
  - cartopy
  - cmocean
  - xgcm
  - python-box
  - tqdm
  - pip
  - pip:
    # Convert jupyter notebooks to python scripts and vice versa
    - jupytext
    # Data downloads
    - datalad
    - datalad-osf
    - gdown
    # Gunnar's code collection
    - "-e git+https://github.com/gunnarvoet/gvpy.git#egg=gvpy"
    # - "-e /Users/gunnar/Projects/python/gvpy"
    # Project package
    - "-e ./code/"
